### ISSUE TITLE
Post your hashes here!

### ISSUE THREAD

**Issue by williamhogman** [klira/ipfs-puzzle-jam#1]

**Comment by machalvan** [comment]
Puzzle: Nian
https://ipfs.io/ipfs/QmTejZuENoGyjxBsggWPS1BreF9iJngas1PtPjAAP2WfsB/

**Comment by profan** [comment]
Cat Memory
http://ipfs.io/ipfs/QmcMXZThNzcBprpJWoS8NexGjAkBi2Yosw9dP1yXis7skK/

**Comment by williamhogman** [comment]
Pinned!
